firstproject/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('gallery/', include('gallery.urls')),
    path('', include('main.urls')), #подключаем файл urls.py из приложения main

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstproject/main/urls.py
from django.urls import path
from django.http import HttpResponse
from .views import AdvertListView, AdvertDetailView, AdvertCreate, AdvertUpdate, AdvertDelete

def testView(request):
    '''
    Тестовый метод для проверки запуска тестовой
    страницы
    '''
    return HttpResponse('<div align="center"><h1 style="color:blue">Это тестовая страница!</h1></div>')

urlpatterns=[
    path('', AdvertListView.as_view(), name='adv_list'),
    path('detail/<int:pk>', AdvertDetailView.as_view(), name='adv_detail'),
    path('create/', AdvertCreate.as_view(), name='adv_create'),
    path('update/<int:pk>', AdvertUpdate.as_view(), name='adv_update'),
    path('delete/<int:pk>', AdvertDelete.as_view(), name='adv_delete'),


]

firstproject/main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.admin import User


def get_path_image(uname, iname):
    ''' Тут формирую имя файла картинки.
     К имени спереди - добавляю путь - папку, с именем пользователя, где будет
     храниться картинка. Если этого не делать, то все фотографии будут в одной папке.'''
    path = str(uname).lower() + '/' + str(iname)
    return path


class Gallery(models.Model):
    ''' Модель Gallery, для хранения информации
     с размером в два поля
    '''
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Описание', max_length=70, blank=True, null=True)

    class Meta:
        ordering = ['title']

    def get_detailUrl(self):
        return reverse('gallery_update', kwargs={'pk': self.pk})

    def get_deleteUrl(self):
        return reverse('gallery_delete', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Advert(models.Model):
    '''
    Модель Advert, для хранения информации рекламного
    обьявления
    '''
    title = models.CharField(verbose_name='заглавие', max_length=50)
    text = models.TextField(verbose_name='Текст обьявления', null=True)
    phone = models.CharField(verbose_name='Телефон', max_length=15, null=True, blank=True)
    email = models.EmailField(verbose_name='правильный Email-адрес', max_length=30, null=True)
    date = models.DateTimeField(auto_now_add=True)
    gallery = models.ForeignKey(Gallery, verbose_name='Галерея', on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Обьявление'
        verbose_name_plural = 'Обьявления'
        ordering = ['-date']

    def get_detailUrl(self):
        return reverse('adv_detail', kwargs={'pk': self.pk})

    def get_absolute_url(self):
        return reverse('adv_list')

    def get_UpdateUrl(self):
        return reverse('adv_update', kwargs={'pk': self.pk})

    def get_DeleteUrl(self):
        return reverse('adv_delete', kwargs={'pk': self.pk})


class Photo(models.Model):
    '''
    Модель Photo, для хранения информации о
    фотографиях
    '''
    title = models.CharField(verbose_name='Описание', max_length=30, blank=True, null=True)
    image = models.ImageField(verbose_name='Фотография', upload_to='gallery/')
    # advert = models.ForeignKey(Advert, verbose_name='Обьявление', on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    gallery = models.ForeignKey(Gallery, verbose_name='Галерея', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'
        ordering = ['user','gallery','title']

    def save(self, *args, **kwargs):
        ''' Переопределяю метод save чтобы изменить значения image.name '''
        self.image.name = get_path_image(self.user, self.image.name)
        super().save(*args, **kwargs)

    def get_PhotodeleteUrl(self):
        return reverse('photo_delete', kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

firstproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Advert</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'adv_list' %}">Advert</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'adv_list' %}">Главная<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Ссылка</a>
      </li>
        {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Меню доступных действий
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'adv_create' %}">Новое обьявление</a>
            <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'gallery_list' %}">Мои галереи</a>
              <a class="dropdown-item" href="{% url 'gallery_create' %}">Новая галерея</a>
              <a class="dropdown-item" href="{% url 'photo_create' %}">Добавить фото</a>
            <div class="dropdown-divider"></div>
          <a class="dropdown-item disabled" href="#">Что-то еще</a>
        </div>
      </li>
        {% endif %}
    </ul>
    &nbsp;
    {% if user.is_authenticated %}
    <a href="{% url 'adv_create' %}" type="button" class="btn btn-outline-info">Создать обьявление</a>
    {% endif %}
    &nbsp;
    &nbsp;
    <form class="form-inline my-2 my-lg-0" action="{% url 'adv_list' %}" method="get">
      <input class="form-control mr-sm-2" name="val" type="search" placeholder="Начните ввод" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
    </form>
    &nbsp;
    {% if user.is_authenticated %}
        <span><b> &nbsp;{{ user.username }}&nbsp; </b></span>
        <a class="nav-link" href="{% url 'account_logout' %}">Выйти</a>
    {% else %}
        <a class="nav-link" href="{% url 'account_login' %}">Вход</a>
        <a class="nav-link" href="{% url 'account_signup' %}">Регистрация</a>
    {% endif %}



  </div>
</nav>


{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

firstproject/templates/paginator.html
{% block paginator %}
{% if is_paginated %}
<nav aria-label="...">
    <ul class="pagination">

        {% if page_obj.has_previous %} <!--Если есть предыдущая страница-->
        <li class="page-item">
            {% if search %}
            <a class="page-link" href="{{ request.path }}?val={{search}}&page={{ page_obj.previous_page_number }}"
               tabindex="-1"
               aria-disabled="true">Previous</a>
            {% else %}
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" tabindex="-1"
               aria-disabled="true">Previous</a>
            {% endif %}
        </li>
        {% else %} <!--Если нет предыдущей страницы-->
        <li class="page-item disabled">
            <a class="page-link" href="">Previous</a>
        </li>
        {% endif %}

        {% for n in paginator.page_range %} <!--Цикл по количеству страниц-->
        {% if page_obj.number == n %} <!--Если это текущая страница-->
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ n }}<span class="sr-only">(current)</span></a>
        </li>
        {% else %} <!--Если это не текущая страница-->
        {% if search %}
        <li class="page-item"><a class="page-link" href="{{ request.path }}?val={{search}}&page={{ n }}">{{ n }}</a>
        </li>
        {% else %}
        <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ n }}">{{ n }}</a></li>
        {% endif %}
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %} <!--Если есть следующая страница-->
        <li class="page-item">
            {% if search %}
            <a class="page-link" href="{{ request.path }}?val={{search}}&page={{ page_obj.next_page_number }}">Next</a>
            {% else %}
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
            {% endif %}
        </li>
        {% else %} <!--Если нету следующей страницы-->
        <li class="page-item disabled">
            <a class="page-link" href="">Next</a>
        </li>
        {% endif %}

    </ul>
</nav>
{% endif %}
{% endblock %}